### ISSUE TITLE
CSS Requirement Missing?

### ISSUE THREAD

**Issue by chrsmlls333** [markusantonwolf/tailwind-css-plugin-multi-columns#4]
When I build in PostCSS, I get this error message:
```
[Error: ENOENT: no such file or directory, open './dist/multi-columns.css'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './dist/multi-columns.css'
}
```
Oddly the few styles I use from your library (".column-2") seem to be working?

---

Using versions:
```json
{
    "@markusantonwolf/tailwind-css-plugin-multi-columns": "^1.1.0",
    "@tailwindcss/typography": "^0.3.1",
    "postcss-cli": "^8.3.1",
    "stylelint-config-recommended": "^5.0.0",
    "tailwindcss": "^2.1.2"
    "..."
}
```

**Comment by markusantonwolf** [comment]
@chrsmlls333 should be fixed in version 1.1.1

**Comment by chrsmlls333** [comment]
Cool, thanks for your promptness! 

I'm pulling directly from the repo here and still seeing the same error FYI

```json
"devDependencies": {
        "@markusantonwolf/tailwind-css-plugin-multi-columns": "github:markusantonwolf/tailwind-css-plugin-multi-columns",
        "..."
}
```

**Comment by markusantonwolf** [comment]
@chrsmlls333 I move all exports to different scripts so it worked without any issues in my tests. Please reinstall the package version 1.1.2 (remove > install): https://www.npmjs.com/package/@markusantonwolf/tailwind-css-plugin-multi-columns

**Comment by chrsmlls333** [comment]
Thanks for your help, all resolved!
